# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 451)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.centralWidgetLayout = QtWidgets.QHBoxLayout()
        self.centralWidgetLayout.setSpacing(6)
        self.centralWidgetLayout.setObjectName("centralWidgetLayout")
        self.mainPaneLayout = QtWidgets.QVBoxLayout()
        self.mainPaneLayout.setObjectName("mainPaneLayout")
        self.canvas = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.canvas.setEnabled(True)
        self.canvas.setMinimumSize(QtCore.QSize(0, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.canvas.setPalette(palette)
        self.canvas.setStyleSheet("")
        self.canvas.setFrameShape(QtWidgets.QFrame.Box)
        self.canvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.canvas.setLineWidth(1)
        self.canvas.setUndoRedoEnabled(False)
        self.canvas.setReadOnly(True)
        self.canvas.setPlainText("")
        self.canvas.setBackgroundVisible(False)
        self.canvas.setPlaceholderText("")
        self.canvas.setObjectName("canvas")
        self.mainPaneLayout.addWidget(self.canvas)
        self.qwrLayout = QtWidgets.QHBoxLayout()
        self.qwrLayout.setObjectName("qwrLayout")
        self.commandEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.commandEdit.setStyleSheet("background-color: transparent; selection-background-color: transparent;  border: 1px solid grey;")
        self.commandEdit.setFrame(False)
        self.commandEdit.setClearButtonEnabled(False)
        self.commandEdit.setObjectName("commandEdit")
        self.qwrLayout.addWidget(self.commandEdit)
        self.queryButton = QtWidgets.QPushButton(self.centralwidget)
        self.queryButton.setObjectName("queryButton")
        self.qwrLayout.addWidget(self.queryButton)
        self.writeButton = QtWidgets.QPushButton(self.centralwidget)
        self.writeButton.setObjectName("writeButton")
        self.qwrLayout.addWidget(self.writeButton)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.qwrLayout.addWidget(self.line_2)
        self.readButton = QtWidgets.QPushButton(self.centralwidget)
        self.readButton.setObjectName("readButton")
        self.qwrLayout.addWidget(self.readButton)
        self.mainPaneLayout.addLayout(self.qwrLayout)
        self.serialPollButton = QtWidgets.QPushButton(self.centralwidget)
        self.serialPollButton.setObjectName("serialPollButton")
        self.mainPaneLayout.addWidget(self.serialPollButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.mainPaneLayout.addWidget(self.clearButton)
        self.centralWidgetLayout.addLayout(self.mainPaneLayout)
        self.sidePanelButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidePanelButton.sizePolicy().hasHeightForWidth())
        self.sidePanelButton.setSizePolicy(sizePolicy)
        self.sidePanelButton.setMinimumSize(QtCore.QSize(0, 0))
        self.sidePanelButton.setMaximumSize(QtCore.QSize(14, 16777215))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sidePanelButton.setFont(font)
        self.sidePanelButton.setCheckable(True)
        self.sidePanelButton.setChecked(False)
        self.sidePanelButton.setFlat(False)
        self.sidePanelButton.setObjectName("sidePanelButton")
        self.centralWidgetLayout.addWidget(self.sidePanelButton)
        self.sidePanel = QtWidgets.QWidget(self.centralwidget)
        self.sidePanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidePanel.sizePolicy().hasHeightForWidth())
        self.sidePanel.setSizePolicy(sizePolicy)
        self.sidePanel.setMinimumSize(QtCore.QSize(360, 0))
        self.sidePanel.setMaximumSize(QtCore.QSize(360, 16777215))
        self.sidePanel.setStyleSheet("")
        self.sidePanel.setObjectName("sidePanel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sidePanel)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sidePaneLayout = QtWidgets.QVBoxLayout()
        self.sidePaneLayout.setObjectName("sidePaneLayout")
        self.tableWidget = QCustomTableWidget(self.sidePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.sidePaneLayout.addWidget(self.tableWidget)
        self.runButton = QtWidgets.QPushButton(self.sidePanel)
        self.runButton.setObjectName("runButton")
        self.sidePaneLayout.addWidget(self.runButton)
        self.verticalLayout_4.addLayout(self.sidePaneLayout)
        self.centralWidgetLayout.addWidget(self.sidePanel)
        self.gridLayout.addLayout(self.centralWidgetLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GPIB Tester"))
        self.commandEdit.setPlaceholderText(_translate("MainWindow", "Example: F, Ft ..."))
        self.queryButton.setText(_translate("MainWindow", "Query"))
        self.writeButton.setText(_translate("MainWindow", "Write"))
        self.readButton.setText(_translate("MainWindow", "Read"))
        self.serialPollButton.setText(_translate("MainWindow", "Serial poll"))
        self.clearButton.setText(_translate("MainWindow", "Clear (bus)"))
        self.sidePanelButton.setText(_translate("MainWindow", ">\n"
">\n"
">\n"
"", "More"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Command"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Argument"))
        self.runButton.setText(_translate("MainWindow", "Run"))

from qcustomtablewidget import QCustomTableWidget
